services:
  - type: web
    name: twilio-webhook-server-1
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 10000
      - key: PUBLIC_BASE
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false

