services:
  - type: web
    name: twilio-webhook-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json
    secretFiles:
      - source: credentials.json
        destination: /etc/secrets/credentials.json


